# Generated by Django 5.1.3 on 2024-11-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_Type', models.CharField(max_length=100)),
                ('Wholesale_Purchase_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Wholesale_Sale_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Retail_Purchase_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Retail_Sale_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/materiales/')),
            ],
        ),
    ]
