# Generated by Django 5.1.3 on 2024-11-24 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day_Report',
            fields=[
                ('Report_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Day', models.DateField(auto_now_add=True)),
                ('Initial_Money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Obtained', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Final_Money', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelTable(
            name='material',
            table='mainapp_material',
        ),
        migrations.CreateModel(
            name='Report_Details',
            fields=[
                ('Detail_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Initial_Stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Final_Stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Sales_Generated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Purchases_Spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Material_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.material')),
                ('Report_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.day_report')),
            ],
        ),
        migrations.AddField(
            model_name='day_report',
            name='Details',
            field=models.ManyToManyField(related_name='reports', through='mainapp.Report_Details', to='mainapp.material'),
        ),
    ]
