# Generated by Django 5.1.3 on 2024-11-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
