# Generated by Django 5.1.3 on 2024-11-28 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_transaction_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_Type', models.CharField(max_length=20)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Action', models.CharField(max_length=20)),
                ('Log_Date', models.DateTimeField(auto_now_add=True)),
                ('Transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.transaction')),
            ],
        ),
    ]
