# Generated by Django 5.1.3 on 2024-11-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_transaction_audit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_audit',
            old_name='Action',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='transaction_audit',
            old_name='Log_Date',
            new_name='log_date',
        ),
        migrations.RenameField(
            model_name='transaction_audit',
            old_name='Total',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='transaction_audit',
            old_name='Transaction',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='transaction_audit',
            old_name='Transaction_Type',
            new_name='transaction_Type',
        ),
    ]
