# Generated by Django 5.1.3 on 2024-11-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_action_transaction_audit_action_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_audit',
            old_name='transaction_Type',
            new_name='transaction_type',
        ),
    ]
