# Generated by Django 5.1.2 on 2024-10-13 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day_Report',
            fields=[
                ('Report_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Day', models.DateField(auto_now_add=True)),
                ('Initial_Money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Obtained', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Final_Money', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('Material_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Material_Type', models.CharField(max_length=100)),
                ('Stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Wholesale_Purchase_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Wholesale_Sale_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Retail_Purchase_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Retail_Sale_Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('Transaction_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(choices=[('COMPLETED', 'Completada'), ('PENDING', 'Pendiente'), ('CANCELED', 'Cancelado')], default='Completada', max_length=10)),
                ('Transaction_Type', models.CharField(choices=[('SALE', 'Venta'), ('Purchase', 'Compra')], max_length=10)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Paternal_Surname', models.CharField(max_length=100)),
                ('Maternal_Surname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=100)),
                ('User_Password', models.CharField(max_length=100)),
                ('User_Privileges', models.CharField(choices=[('admin', 'admin'), ('worker', 'worker')], default='worker', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Report_Details',
            fields=[
                ('Detail_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Initial_Stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Final_Stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Sales_Generated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Purchases_Spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Material_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.material')),
                ('Report_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.day_report')),
            ],
        ),
        migrations.AddField(
            model_name='day_report',
            name='Details',
            field=models.ManyToManyField(related_name='reports', through='main_app.Report_Details', to='main_app.material'),
        ),
        migrations.CreateModel(
            name='Transaction_Details',
            fields=[
                ('Detail_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Material_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.material')),
                ('Transaction_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='Details',
            field=models.ManyToManyField(related_name='transactions', through='main_app.Transaction_Details', to='main_app.material'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='User_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.users'),
        ),
    ]
