# Generated by Django 5.1.2 on 2024-10-23 04:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material_Type', models.CharField(max_length=100)),
                ('Wholesale_Purchase_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Wholesale_Sale_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Retail_Purchase_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Retail_Sale_Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Name', models.CharField(max_length=100)),
                ('Paternal_Surname', models.CharField(max_length=100)),
                ('Maternal_Surname', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(choices=[('COMPLETED', 'Completada'), ('PENDING', 'Pendiente'), ('CANCELED', 'Cancelado')], default='Completada', max_length=10)),
                ('Transaction_Type', models.CharField(choices=[('SALE', 'Venta'), ('PURCHASE', 'Compra')], max_length=10)),
                ('Description', models.CharField(max_length=100)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.material')),
                ('Transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='Details',
            field=models.ManyToManyField(related_name='transactions', through='main_app.Transaction_Details', to='main_app.material'),
        ),
    ]
